In [34]:
import torch

In [73]:
x = torch.Tensor(5,3) #initialize x by a matrix of 5*3

print(x)

x = torch.rand(5,3) #random matrix

print(x)


    0.0000     0.0000     0.0000
    0.0000     0.0000     0.0000
-4946.7812     0.0000     0.0000
    0.0000     0.0000     0.0000
-6229.8984     0.0000     0.0000
[torch.FloatTensor of size 5x3]


 0.1322  0.4108  0.8241
 0.1099  0.4665  0.6269
 0.1151  0.2304  0.9171
 0.4578  0.0448  0.2548
 0.6515  0.8520  0.3075
[torch.FloatTensor of size 5x3]



In [36]:
print(x.size()) #matrix size

torch.Size([5, 3])


In [37]:
y = torch.rand(5,3)

print(x+y)


 0.6300  1.0836  1.4167
 0.7921  0.9554  0.8558
 1.6717  1.7936  1.1050
 1.1185  1.4546  1.2807
 0.1397  0.0952  0.8110
[torch.FloatTensor of size 5x3]



In [38]:
print(torch.add(x,y))


 0.6300  1.0836  1.4167
 0.7921  0.9554  0.8558
 1.6717  1.7936  1.1050
 1.1185  1.4546  1.2807
 0.1397  0.0952  0.8110
[torch.FloatTensor of size 5x3]



In [39]:
result = torch.Tensor(5,3)

In [40]:
torch.add(x,y,out=result)
print(result) # result = x+y


 0.6300  1.0836  1.4167
 0.7921  0.9554  0.8558
 1.6717  1.7936  1.1050
 1.1185  1.4546  1.2807
 0.1397  0.0952  0.8110
[torch.FloatTensor of size 5x3]



In [45]:
y.add_(x) # y = y + x
print(y)


 1.3835  4.4792  4.7466
 3.2088  4.1954  3.2482
 5.5665  5.6399  3.4081
 2.3603  4.6288  3.3449
 0.3926  0.3645  2.6105
[torch.FloatTensor of size 5x3]



In [74]:
print(x[:,1]) #print second column


 0.4108
 0.4665
 0.2304
 0.0448
 0.8520
[torch.FloatTensor of size 5]



In [77]:
print(x[1,:]) #print second row


 0.1099
 0.4665
 0.6269
[torch.FloatTensor of size 3]



In [104]:
a = torch.ones(5)  #5 1s
print(a)

b = a.numpy()
print(b)


 1
 1
 1
 1
 1
[torch.FloatTensor of size 5]

[ 1.  1.  1.  1.  1.]


In [88]:
a.add_(1) #changing the np array changed the torch Tensor automatically
print(a)
print(b)


 2
 2
 2
 2
 2
[torch.FloatTensor of size 5]

[ 2.  2.  2.  2.  2.]


In [105]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a,1,out=a)
print(a)
print(b) #changing the np array changed the torch Tensor automatically

[ 2.  2.  2.  2.  2.]

 2
 2
 2
 2
 2
[torch.DoubleTensor of size 5]



In [107]:
if torch.cuda.is_available():
    x = x.cuda()
    y = y.cuda()
    x+y